#-------------------- 
# SHOUGO-SAN'S
#-------------------- 
[[plugins]]
repo = '$HOME/.cache/dein/repos/github.com/Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

#-------------------- 
# AIRLINE
#-------------------- 
[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
" powerline形式で表示
set laststatus=2
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
let g:airline_theme = 'papercolor'
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#-------------------- 
# OPERATOR
#-------------------- 
[[plugins]]
repo = 'kana/vim-operator-user'
depends = ['vim-operator-replace']

[[plugins]]
repo = 'kana/vim-operator-replace'
hook_add = '''
" yankした文字列と対象の置換
map R <Plug>(operator-replace)
'''

[[plugins]]
repo = 'rhysd/vim-operator-surround'
hook_add = '''
" operator mappings
" append surround <text object>
map <silent>as <Plug>(operator-surround-append)
" delete surround a <text object>
map <silent>ds <Plug>(operator-surround-delete)
" replace surround a <text object>
map <silent>rs <Plug>(operator-surround-replace)
'''

[[plugins]]
repo = 'LeafCage/yankround.vim'
hook_add = '''
nmap p <Plug>(yankround-p)
xmap p <Plug>(yankround-p)
nmap P <Plug>(yankround-P)
nmap gp <Plug>(yankround-gp)
xmap gp <Plug>(yankround-gp)
nmap gP <Plug>(yankround-gP)
nmap <C-p> <Plug>(yankround-prev)
nmap <C-n> <Plug>(yankround-next)
'''

#-------------------- 
# YANK/PASTE/SERACH/HIGHLIGHT
#-------------------- 
[[plugins]]
repo = 'machakann/vim-highlightedyank'

[[plugins]]
repo = 'thinca/vim-visualstar'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
vmap <S-v> <Plug>(expand_region_expand)
vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'kqito/vim-easy-replace'

#-------------------- 
# MOVEMENT
#-------------------- 
[[plugins]]
repo = 'yuttie/comfortable-motion.vim'

[[plugins]]
repo = 'rhysd/accelerated-jk'
hook_add = '''
nmap j <Plug>(accelerated_jk_gj)
nmap k <Plug>(accelerated_jk_gk)
let g:accelerated_jk_acceleration_limit = 1
'''

[[plugins]]
repo = 'rhysd/clever-f.vim'
hook_add ='''
" 大文字小文字を無視
let g:clever_f_ignore_case = 1
" 任意の記号にマッチする文字を設定
let g:clever_f_chars_match_any_signs = ';'
'''

#-------------------- 
# OTHERS
#-------------------- 
[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
let g:indentLine_char = '|'
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tomasr/molokai'
